# Generated by Django 3.2.3 on 2021-06-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_categorymodel_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='parent_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='_book_categorymodel_parent_category_+', to='book.CategoryModel'),
        ),
    ]
