# Generated by Django 3.2.3 on 2021-06-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210602_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='parent_category',
            field=models.ManyToManyField(blank=True, related_name='_book_categorymodel_parent_category_+', to='book.CategoryModel'),
        ),
    ]
