# Generated by Django 3.2.3 on 2021-06-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_categorymodel_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_categ', to='book.categorymodel'),
        ),
    ]
