# Generated by Django 3.2.3 on 2021-06-01 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('generalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.generalmodel')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nit', models.SmallIntegerField()),
                ('birthday', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
            options={
                'verbose_name': 'Lector',
                'verbose_name_plural': 'Lectores',
                'ordering': ['last_name'],
            },
            bases=('utils.generalmodel',),
        ),
        migrations.CreateModel(
            name='LoanModel',
            fields=[
                ('generalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.generalmodel')),
                ('loan_date', models.DateTimeField()),
                ('restore_date', models.DateTimeField(blank=True, null=True)),
                ('restored', models.BooleanField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_loan', to='book.bookmodel')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_loan', to='person.personmodel')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
            },
            bases=('utils.generalmodel',),
        ),
    ]
