# Generated by Django 3.2.3 on 2021-06-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='foto_lectores'),
        ),
    ]
