# Generated by Django 3.2.3 on 2021-06-01 20:41

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('generalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.generalmodel')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('birthday', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['last_name'],
            },
            bases=('utils.generalmodel',),
        ),
    ]
